(function(){
  const esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;","}":"&gt;",'\"':"&quot;","'":"&#39;"}[c]));
  const sf=(r,keys)=>{for(const k of keys){if(r&&r[k]!==undefined&&String(r[k]??"").trim()!=="")return r[k]}return""};
  const cn=r=>sf(r,["CONTAINER NO.","CONTAINER","CONTAINER NO","CNTR NO"]);
  const status=r=>sf(r,["CONTAINER RETURN DATE"])?"RETURNED":sf(r,["DESTUFFING DATE"])?"DE-STUFFED":sf(r,["CFS IN"])?"CFS IN":sf(r,["PORT OUT"])?"PORT OUT":sf(r,["PORT IN"])?"PORT IN":sf(r,["INWARD DATE"])?"INWARD GRANTED":sf(r,["ETD"])?"IN TRANSIT":"PENDING";
  const statusDate=r=>({"RETURNED":"CONTAINER RETURN DATE","DE-STUFFED":"DESTUFFING DATE","CFS IN":"CFS IN","PORT OUT":"PORT OUT","PORT IN":"PORT IN","INWARD GRANTED":"INWARD DATE","IN TRANSIT":"ETD"}[status(r)]||"");
  const fmt=v=>{if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})};
  function build(list){
    const generated=new Date().toLocaleDateString("en-IN",{day:"2-digit",month:"long",year:"numeric"});
    return '<div style="width:1400px;background:#fff;color:#18384b;padding:54px 64px;font-family:Arial,sans-serif;box-sizing:border-box">'+
      '<div style="display:flex;justify-content:space-between;align-items:flex-start;border-bottom:3px solid #17384a;padding-bottom:18px"><div><div style="font-size:14px;font-weight:800;letter-spacing:2.5px;color:#0878b5">SHIPMENT STATUS</div><div style="font-size:38px;font-weight:800;margin-top:7px">'+esc((window.GML_APP_CONFIG&&GML_APP_CONFIG.appName)||"Shipment Operations")+'</div></div><div style="text-align:right;font-size:12px;color:#71838c"><b style="display:block;color:#18384b;font-size:14px">GENERATED</b>'+generated+'</div></div>'+ 
      list.map(r=>{const s=status(r),d=statusDate(r);return '<div style="margin-top:24px;border:1px solid #d8e2e7;padding:22px"><div style="display:flex;justify-content:space-between;gap:20px;align-items:flex-start"><div><div style="font-size:11px;color:#84949c;letter-spacing:1px">CONTAINER</div><div style="font-size:22px;font-weight:800;font-family:monospace;margin-top:4px">'+esc(cn(r)||"—")+'</div></div><div style="text-align:right"><div style="font-size:10px;color:#84949c;letter-spacing:1px">CURRENT STATUS</div><div style="display:flex;align-items:center;justify-content:flex-end;gap:10px;margin-top:6px"><span style="display:inline-block;padding:8px 12px;background:#eaf5fa;color:#0878b5;font-size:13px;font-weight:800">'+esc(s)+'</span><span style="font-size:13px;font-weight:800;color:#18384b">'+esc(fmt(d))+'</span></div></div></div><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:22px;margin-top:26px;font-size:13px"><div><span style="display:block;color:#8a989f">MBL</span><b>'+esc(sf(r,["MBL NO","MBL"]))+'</b></div><div><span style="display:block;color:#8a989f">VESSEL / VOYAGE</span><b>'+esc(sf(r,["VESSEL & VOY","VESSEL"]))+'</b></div><div><span style="display:block;color:#8a989f">POL</span><b>'+esc(sf(r,["POL"]))+'</b></div><div><span style="display:block;color:#8a989f">GATEWAY</span><b>'+esc(sf(r,["GATEWAY PORT"]))+'</b></div></div></div>'}).join("")+
      '<div style="margin-top:24px;padding-top:16px;border-top:1px solid #d8e2e7;font-size:11px;color:#82929a">Generated from live shipment records • '+generated+'</div></div>';
  }
  function attach(){
    const b=document.getElementById("statusPhotoBtn");if(!b||!window.html2canvas)return;
    const fresh=b.cloneNode(true);b.replaceWith(fresh);
    fresh.addEventListener("click",async()=>{const list=window.selectedRows?window.selectedRows():[];const data=list.length?list:(window.filtered?window.filtered():[]);if(!data.length){window.notify&&window.notify("Select at least one shipment first.");return}const wrap=document.createElement("div");wrap.style.cssText="position:fixed;left:-10000px;top:0;z-index:-1";wrap.innerHTML=build(data);document.body.appendChild(wrap);try{const canvas=await html2canvas(wrap.firstElementChild,{scale:2.5,backgroundColor:"#fff",useCORS:true,windowWidth:1500});const a=document.createElement("a");a.download="Shipment_Status_"+new Date().toISOString().slice(0,10)+".png";a.href=canvas.toDataURL("image/png");a.click();window.notify&&window.notify("High-resolution status photo created.")}catch(e){console.error(e);window.notify&&window.notify("Unable to create status photo")}finally{wrap.remove()}});
  }
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(attach,150));else setTimeout(attach,150);
})();
